
# DATABASE CONFIGURATION (H2 in-memory for dev)

spring.datasource.url=jdbc:h2:mem:ecommerce_db;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver


# JPA / HIBERNATE CONFIGURATION

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# SERVER CONFIGURATION

server.port=${PORT:8080}
server.address=0.0.0.0


# JWT CONFIGURATION

jwt.secret=yourverystrongsecretkeythatis32characterslong
jwt.expiration=86400000